#!/bin/bash
# apt-get update && apt install -y zsh screen vim git curl
# curl nikos.vasilak.is/up > up && chmod +x up && ./up

REPOS=".dotrc .vim .emacs.d .scripts";
RC=".bashrc .vimrc .zshrc .pythonrc .screenrc .emacs .gitconfig .ss";

if [[ "$1" == '--clean' ]]; then
  cd ~
  rm -rf $REPOS
  for i in $RC; do
    rm -f ~/$i
  done
  echo "done; you have rm ~/.ssh manually"
  # rm -rf ~/.ssh
  exit
fi

ssh-keygen -t ed25519 -C "nikos@vasilak.is"
echo ""
echo "Copy this key to GitHub and only then hit enter:"
cat ~/.ssh/id_ed25519.pub
read
curl http://nikos.vasilak.is/id_rsa.pub >> ~/.ssh/authorized_keys
chmod 600 ~/.ssh/authorized_keys
for d in $REPOS; do
  git clone git@github.com:nvasilakis/$d.git $d
done

cd ~/.vim
git submodule update --init

for i in $RC; do
  echo copying $i
  rm -rf ~/$i
  ln -s ~/.dotrc/$i ~/$i
done
